-- Seed Data: 157+ Popular AI Tools with Logos
-- Run this AFTER the main migration.sql

-- Get category IDs for reference
DO $$
DECLARE
  cat_writing UUID;
  cat_image UUID;
  cat_video UUID;
  cat_audio UUID;
  cat_coding UUID;
  cat_productivity UUID;
  cat_marketing UUID;
  cat_chatbots UUID;
  cat_design UUID;
BEGIN
  SELECT id INTO cat_writing FROM categories WHERE slug = 'writing';
  SELECT id INTO cat_image FROM categories WHERE slug = 'image-generation';
  SELECT id INTO cat_video FROM categories WHERE slug = 'video';
  SELECT id INTO cat_audio FROM categories WHERE slug = 'audio';
  SELECT id INTO cat_coding FROM categories WHERE slug = 'coding';
  SELECT id INTO cat_productivity FROM categories WHERE slug = 'productivity';
  SELECT id INTO cat_marketing FROM categories WHERE slug = 'marketing';
  SELECT id INTO cat_chatbots FROM categories WHERE slug = 'chatbots';
  SELECT id INTO cat_design FROM categories WHERE slug = 'design';

  -- =============================================
  -- CHATBOTS & AI ASSISTANTS (20 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('ChatGPT', 'chatgpt', 'AI-powered conversational assistant by OpenAI', 'ChatGPT is an AI language model that can understand and generate human-like text. Perfect for writing, coding, analysis, and creative tasks.', 'https://chat.openai.com', cat_chatbots, 'freemium', 'approved', ARRAY['chatbot', 'writing', 'coding', 'popular'], 'https://logo.clearbit.com/openai.com'),
  ('Claude', 'claude', 'Helpful, harmless, and honest AI assistant by Anthropic', 'Claude is an AI assistant trained to be helpful, harmless, and honest. Excellent for analysis, writing, coding, and research tasks.', 'https://claude.ai', cat_chatbots, 'freemium', 'approved', ARRAY['chatbot', 'writing', 'analysis', 'popular'], 'https://logo.clearbit.com/anthropic.com'),
  ('Gemini', 'gemini', 'Google''s most capable AI model', 'Gemini is Google''s largest and most capable AI model, built to be multimodal from the ground up.', 'https://gemini.google.com', cat_chatbots, 'freemium', 'approved', ARRAY['chatbot', 'multimodal', 'google'], 'https://logo.clearbit.com/google.com'),
  ('Perplexity', 'perplexity', 'AI-powered answer engine with real-time search', 'Perplexity combines AI with real-time web search to provide accurate, sourced answers to your questions.', 'https://perplexity.ai', cat_chatbots, 'freemium', 'approved', ARRAY['search', 'research', 'answers'], 'https://logo.clearbit.com/perplexity.ai'),
  ('Microsoft Copilot', 'microsoft-copilot', 'AI assistant integrated across Microsoft products', 'Microsoft Copilot brings AI assistance to Windows, Office, and Edge for enhanced productivity.', 'https://copilot.microsoft.com', cat_chatbots, 'freemium', 'approved', ARRAY['chatbot', 'microsoft', 'productivity'], 'https://logo.clearbit.com/microsoft.com'),
  ('Pi', 'pi-ai', 'Personal AI assistant for meaningful conversations', 'Pi by Inflection AI is designed for extended, personal conversations with emotional intelligence.', 'https://pi.ai', cat_chatbots, 'free', 'approved', ARRAY['chatbot', 'personal', 'conversation'], 'https://logo.clearbit.com/inflection.ai'),
  ('Poe', 'poe', 'Access multiple AI models in one platform', 'Poe by Quora lets you chat with various AI models including GPT-4, Claude, and custom bots.', 'https://poe.com', cat_chatbots, 'freemium', 'approved', ARRAY['chatbot', 'aggregator', 'multi-model'], 'https://logo.clearbit.com/poe.com'),
  ('Character.AI', 'character-ai', 'Chat with AI-powered characters and personalities', 'Character.AI lets you create and chat with AI characters based on real or fictional personalities.', 'https://character.ai', cat_chatbots, 'freemium', 'approved', ARRAY['chatbot', 'roleplay', 'characters'], 'https://logo.clearbit.com/character.ai'),
  ('Replika', 'replika', 'AI companion for emotional support', 'Replika is an AI friend that learns from your conversations and provides companionship.', 'https://replika.ai', cat_chatbots, 'freemium', 'approved', ARRAY['companion', 'mental-health', 'personal'], 'https://logo.clearbit.com/replika.ai'),
  ('You.com', 'you-com', 'AI search engine with chat capabilities', 'You.com combines AI chat with web search for comprehensive, sourced answers.', 'https://you.com', cat_chatbots, 'freemium', 'approved', ARRAY['search', 'chat', 'research'], 'https://logo.clearbit.com/you.com'),
  ('Cohere', 'cohere', 'Enterprise AI for business applications', 'Cohere provides enterprise-grade AI models for text generation, classification, and search.', 'https://cohere.com', cat_chatbots, 'enterprise', 'approved', ARRAY['enterprise', 'api', 'nlp'], 'https://logo.clearbit.com/cohere.com'),
  ('Hugging Face', 'hugging-face', 'The AI community and model hub', 'Hugging Face is the leading platform for sharing and deploying machine learning models.', 'https://huggingface.co', cat_chatbots, 'freemium', 'approved', ARRAY['models', 'open-source', 'community'], 'https://logo.clearbit.com/huggingface.co'),
  ('Llama', 'llama', 'Meta''s open-source large language model', 'Llama by Meta is an open-source LLM available for research and commercial use.', 'https://llama.meta.com', cat_chatbots, 'free', 'approved', ARRAY['open-source', 'llm', 'meta'], 'https://logo.clearbit.com/meta.com'),
  ('Mistral AI', 'mistral-ai', 'European AI lab building efficient models', 'Mistral AI creates efficient, open-weight language models competitive with larger alternatives.', 'https://mistral.ai', cat_chatbots, 'freemium', 'approved', ARRAY['llm', 'open-source', 'efficient'], 'https://logo.clearbit.com/mistral.ai'),
  ('Groq', 'groq', 'Ultra-fast AI inference platform', 'Groq provides the fastest AI inference with their custom LPU hardware.', 'https://groq.com', cat_chatbots, 'freemium', 'approved', ARRAY['fast', 'inference', 'hardware'], 'https://logo.clearbit.com/groq.com'),
  ('Together AI', 'together-ai', 'Run open-source AI models at scale', 'Together AI provides infrastructure to run and fine-tune open-source AI models.', 'https://together.ai', cat_chatbots, 'freemium', 'approved', ARRAY['infrastructure', 'open-source', 'api'], 'https://logo.clearbit.com/together.ai'),
  ('Anyscale', 'anyscale', 'Scale AI applications with Ray', 'Anyscale provides the platform to build and scale AI applications using Ray.', 'https://anyscale.com', cat_chatbots, 'enterprise', 'approved', ARRAY['infrastructure', 'scaling', 'enterprise'], 'https://logo.clearbit.com/anyscale.com'),
  ('Forefront', 'forefront', 'Access advanced AI models for free', 'Forefront provides free access to GPT-4 and Claude with a clean interface.', 'https://forefront.ai', cat_chatbots, 'freemium', 'approved', ARRAY['chat', 'free', 'multi-model'], 'https://logo.clearbit.com/forefront.ai'),
  ('DeepSeek', 'deepseek', 'Chinese AI lab with competitive models', 'DeepSeek creates powerful AI models with strong reasoning capabilities.', 'https://deepseek.com', cat_chatbots, 'freemium', 'approved', ARRAY['llm', 'reasoning', 'coding'], 'https://logo.clearbit.com/deepseek.com'),
  ('Khanmigo', 'khanmigo', 'AI tutor by Khan Academy', 'Khanmigo is an AI-powered tutor that helps students learn with personalized guidance.', 'https://khanacademy.org/khan-labs', cat_chatbots, 'paid', 'approved', ARRAY['education', 'tutor', 'learning'], 'https://logo.clearbit.com/khanacademy.org')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- IMAGE GENERATION (25 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('Midjourney', 'midjourney', 'AI art generator creating stunning images from text', 'Midjourney is an AI-powered tool that generates images from natural language descriptions, known for artistic and creative outputs.', 'https://midjourney.com', cat_image, 'paid', 'approved', ARRAY['art', 'image', 'creative', 'popular'], 'https://logo.clearbit.com/midjourney.com'),
  ('DALL-E 3', 'dall-e-3', 'OpenAI''s advanced image generation model', 'DALL-E 3 creates realistic images and art from natural language descriptions with improved accuracy and detail.', 'https://openai.com/dall-e-3', cat_image, 'paid', 'approved', ARRAY['image', 'art', 'openai'], 'https://logo.clearbit.com/openai.com'),
  ('Stable Diffusion', 'stable-diffusion', 'Open-source AI image generation model', 'Stable Diffusion is an open-source AI model that generates images from text prompts, available for local use and customization.', 'https://stability.ai', cat_image, 'freemium', 'approved', ARRAY['image', 'open-source', 'art'], 'https://logo.clearbit.com/stability.ai'),
  ('Leonardo AI', 'leonardo-ai', 'AI image generation for game assets and art', 'Leonardo AI specializes in generating game assets, concept art, and creative images with fine-tuned control.', 'https://leonardo.ai', cat_image, 'freemium', 'approved', ARRAY['image', 'gaming', 'art'], 'https://logo.clearbit.com/leonardo.ai'),
  ('Ideogram', 'ideogram', 'AI image generator with excellent text rendering', 'Ideogram excels at generating images with accurate text, logos, and typography embedded naturally.', 'https://ideogram.ai', cat_image, 'freemium', 'approved', ARRAY['image', 'text', 'logos'], 'https://logo.clearbit.com/ideogram.ai'),
  ('Adobe Firefly', 'adobe-firefly', 'AI image generation integrated with Creative Cloud', 'Adobe Firefly brings generative AI to Photoshop and other Adobe apps for creative professionals.', 'https://firefly.adobe.com', cat_image, 'freemium', 'approved', ARRAY['image', 'adobe', 'creative'], 'https://logo.clearbit.com/adobe.com'),
  ('Playground AI', 'playground-ai', 'Free AI image generator with editing tools', 'Playground AI offers free image generation with canvas editing and multiple model options.', 'https://playground.com', cat_image, 'freemium', 'approved', ARRAY['image', 'free', 'editing'], 'https://logo.clearbit.com/playground.com'),
  ('NightCafe', 'nightcafe', 'AI art generator with multiple algorithms', 'NightCafe offers various AI art generation algorithms and a vibrant creator community.', 'https://nightcafe.studio', cat_image, 'freemium', 'approved', ARRAY['art', 'community', 'algorithms'], 'https://logo.clearbit.com/nightcafe.studio'),
  ('Lexica', 'lexica', 'Stable Diffusion search engine and generator', 'Lexica lets you search millions of AI-generated images and create your own.', 'https://lexica.art', cat_image, 'freemium', 'approved', ARRAY['search', 'stable-diffusion', 'gallery'], 'https://logo.clearbit.com/lexica.art'),
  ('DreamStudio', 'dreamstudio', 'Official Stable Diffusion web interface', 'DreamStudio is Stability AI''s official platform for Stable Diffusion image generation.', 'https://dreamstudio.ai', cat_image, 'freemium', 'approved', ARRAY['stable-diffusion', 'official', 'image'], 'https://logo.clearbit.com/stability.ai'),
  ('Bing Image Creator', 'bing-image-creator', 'Free AI image generation powered by DALL-E', 'Microsoft''s Bing Image Creator uses DALL-E to generate images for free.', 'https://bing.com/images/create', cat_image, 'free', 'approved', ARRAY['free', 'dall-e', 'microsoft'], 'https://logo.clearbit.com/bing.com'),
  ('Craiyon', 'craiyon', 'Free AI image generator (formerly DALL-E mini)', 'Craiyon is a free AI image generator that creates images from text descriptions.', 'https://craiyon.com', cat_image, 'free', 'approved', ARRAY['free', 'image', 'simple'], 'https://logo.clearbit.com/craiyon.com'),
  ('Artbreeder', 'artbreeder', 'Collaborative AI image creation and mixing', 'Artbreeder lets you blend and evolve images using AI to create unique artwork.', 'https://artbreeder.com', cat_image, 'freemium', 'approved', ARRAY['creative', 'collaboration', 'mixing'], 'https://logo.clearbit.com/artbreeder.com'),
  ('Wombo Dream', 'wombo-dream', 'AI art generator mobile app', 'Wombo Dream turns your words into stunning AI artwork on mobile devices.', 'https://dream.ai', cat_image, 'freemium', 'approved', ARRAY['mobile', 'art', 'app'], 'https://logo.clearbit.com/wombo.ai'),
  ('Scenario', 'scenario', 'AI image generation for game developers', 'Scenario specializes in generating consistent game assets and characters using AI.', 'https://scenario.com', cat_image, 'freemium', 'approved', ARRAY['gaming', 'assets', 'consistent'], 'https://logo.clearbit.com/scenario.com'),
  ('Krea AI', 'krea-ai', 'Real-time AI image generation and enhancement', 'Krea AI generates and enhances images in real-time as you draw or describe.', 'https://krea.ai', cat_image, 'freemium', 'approved', ARRAY['real-time', 'enhancement', 'creative'], 'https://logo.clearbit.com/krea.ai'),
  ('Hotpot AI', 'hotpot-ai', 'AI tools for graphics and image editing', 'Hotpot AI offers image generation, restoration, and enhancement tools.', 'https://hotpot.ai', cat_image, 'freemium', 'approved', ARRAY['graphics', 'editing', 'restoration'], 'https://logo.clearbit.com/hotpot.ai'),
  ('StarryAI', 'starryai', 'AI art generator with NFT creation', 'StarryAI generates artwork and makes it easy to mint as NFTs.', 'https://starryai.com', cat_image, 'freemium', 'approved', ARRAY['art', 'nft', 'mobile'], 'https://logo.clearbit.com/starryai.com'),
  ('Deep Dream Generator', 'deep-dream', 'Artistic AI image transformation', 'Deep Dream Generator creates psychedelic and artistic transformations of images.', 'https://deepdreamgenerator.com', cat_image, 'freemium', 'approved', ARRAY['artistic', 'transformation', 'psychedelic'], 'https://logo.clearbit.com/deepdreamgenerator.com'),
  ('Photosonic', 'photosonic', 'AI image generator by Writesonic', 'Photosonic creates images from text descriptions using advanced AI models.', 'https://photosonic.ai', cat_image, 'freemium', 'approved', ARRAY['image', 'text-to-image', 'writesonic'], 'https://logo.clearbit.com/writesonic.com'),
  ('Clipdrop', 'clipdrop', 'AI-powered image editing suite', 'Clipdrop offers AI tools for background removal, upscaling, and image generation.', 'https://clipdrop.co', cat_image, 'freemium', 'approved', ARRAY['editing', 'background', 'upscaling'], 'https://logo.clearbit.com/clipdrop.co'),
  ('Fotor AI', 'fotor-ai', 'AI photo editing and generation', 'Fotor AI combines traditional photo editing with AI generation capabilities.', 'https://fotor.com', cat_image, 'freemium', 'approved', ARRAY['editing', 'photo', 'generation'], 'https://logo.clearbit.com/fotor.com'),
  ('PicWish', 'picwish', 'AI background remover and editor', 'PicWish removes backgrounds and edits photos using AI technology.', 'https://picwish.com', cat_image, 'freemium', 'approved', ARRAY['background', 'removal', 'editing'], 'https://logo.clearbit.com/picwish.com'),
  ('Lensa AI', 'lensa-ai', 'AI photo editor with magic avatars', 'Lensa AI creates stylized portraits and avatars from your photos.', 'https://prisma-ai.com/lensa', cat_image, 'freemium', 'approved', ARRAY['portraits', 'avatars', 'photo'], 'https://logo.clearbit.com/prisma-ai.com'),
  ('Flux', 'flux', 'Fast open-source image generation model', 'Flux by Black Forest Labs offers fast, high-quality image generation.', 'https://blackforestlabs.ai', cat_image, 'freemium', 'approved', ARRAY['fast', 'open-source', 'quality'], 'https://logo.clearbit.com/blackforestlabs.ai')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- WRITING & CONTENT (20 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('Jasper', 'jasper', 'AI writing assistant for marketing teams', 'Jasper helps marketing teams create high-quality content faster with AI-powered writing assistance.', 'https://jasper.ai', cat_writing, 'paid', 'approved', ARRAY['writing', 'marketing', 'content'], 'https://logo.clearbit.com/jasper.ai'),
  ('Copy.ai', 'copy-ai', 'AI copywriting tool for marketing content', 'Copy.ai generates marketing copy, blog posts, and social media content using AI.', 'https://copy.ai', cat_writing, 'freemium', 'approved', ARRAY['writing', 'copywriting', 'marketing'], 'https://logo.clearbit.com/copy.ai'),
  ('Writesonic', 'writesonic', 'AI writer for blogs, ads, and more', 'Writesonic creates SEO-optimized content, ads, and product descriptions using AI.', 'https://writesonic.com', cat_writing, 'freemium', 'approved', ARRAY['writing', 'seo', 'content'], 'https://logo.clearbit.com/writesonic.com'),
  ('Grammarly', 'grammarly', 'AI-powered writing assistant', 'Grammarly helps you write mistake-free with AI-powered grammar, spelling, and style suggestions.', 'https://grammarly.com', cat_writing, 'freemium', 'approved', ARRAY['writing', 'grammar', 'editing', 'popular'], 'https://logo.clearbit.com/grammarly.com'),
  ('QuillBot', 'quillbot', 'AI paraphrasing and writing tool', 'QuillBot helps you rewrite and paraphrase text while maintaining meaning and improving clarity.', 'https://quillbot.com', cat_writing, 'freemium', 'approved', ARRAY['writing', 'paraphrase', 'editing'], 'https://logo.clearbit.com/quillbot.com'),
  ('Rytr', 'rytr', 'AI writing assistant for content creation', 'Rytr generates high-quality content in seconds with 30+ use cases and 30+ languages.', 'https://rytr.me', cat_writing, 'freemium', 'approved', ARRAY['writing', 'content', 'multilingual'], 'https://logo.clearbit.com/rytr.me'),
  ('Wordtune', 'wordtune', 'AI writing companion for better expression', 'Wordtune helps you rewrite sentences to be clearer, more compelling, or more professional.', 'https://wordtune.com', cat_writing, 'freemium', 'approved', ARRAY['writing', 'rewriting', 'clarity'], 'https://logo.clearbit.com/wordtune.com'),
  ('Anyword', 'anyword', 'AI copywriting with predictive analytics', 'Anyword generates marketing copy and predicts performance before publishing.', 'https://anyword.com', cat_writing, 'paid', 'approved', ARRAY['marketing', 'predictive', 'copy'], 'https://logo.clearbit.com/anyword.com'),
  ('Writer', 'writer', 'Enterprise AI writing platform', 'Writer provides AI writing assistance with brand consistency for enterprises.', 'https://writer.com', cat_writing, 'enterprise', 'approved', ARRAY['enterprise', 'brand', 'consistency'], 'https://logo.clearbit.com/writer.com'),
  ('Peppertype', 'peppertype', 'AI content generation platform', 'Peppertype generates marketing content, blogs, and product descriptions using AI.', 'https://peppertype.ai', cat_writing, 'freemium', 'approved', ARRAY['content', 'marketing', 'generation'], 'https://logo.clearbit.com/peppertype.ai'),
  ('Copysmith', 'copysmith', 'AI copywriting for ecommerce', 'Copysmith specializes in generating product descriptions and marketing copy at scale.', 'https://copysmith.ai', cat_writing, 'paid', 'approved', ARRAY['ecommerce', 'product', 'descriptions'], 'https://logo.clearbit.com/copysmith.ai'),
  ('Simplified', 'simplified', 'AI content creation and design platform', 'Simplified combines AI writing with design tools for content creators.', 'https://simplified.com', cat_writing, 'freemium', 'approved', ARRAY['writing', 'design', 'all-in-one'], 'https://logo.clearbit.com/simplified.com'),
  ('ContentBot', 'contentbot', 'AI content automation platform', 'ContentBot automates blog writing and content creation with AI.', 'https://contentbot.ai', cat_writing, 'freemium', 'approved', ARRAY['automation', 'blog', 'content'], 'https://logo.clearbit.com/contentbot.ai'),
  ('Hypotenuse AI', 'hypotenuse-ai', 'AI writing for ecommerce and marketing', 'Hypotenuse AI generates product descriptions, blog posts, and marketing content.', 'https://hypotenuse.ai', cat_writing, 'paid', 'approved', ARRAY['ecommerce', 'marketing', 'batch'], 'https://logo.clearbit.com/hypotenuse.ai'),
  ('Longshot AI', 'longshot-ai', 'AI for long-form content and fact-checking', 'Longshot AI creates factually accurate long-form content with built-in research.', 'https://longshot.ai', cat_writing, 'freemium', 'approved', ARRAY['long-form', 'research', 'facts'], 'https://logo.clearbit.com/longshot.ai'),
  ('Narrato', 'narrato', 'AI content workspace for teams', 'Narrato combines AI writing with workflow tools for content teams.', 'https://narrato.io', cat_writing, 'freemium', 'approved', ARRAY['workflow', 'team', 'content'], 'https://logo.clearbit.com/narrato.io'),
  ('Scalenut', 'scalenut', 'AI-powered SEO content platform', 'Scalenut helps create SEO-optimized content with AI-powered research and writing.', 'https://scalenut.com', cat_writing, 'freemium', 'approved', ARRAY['seo', 'research', 'optimization'], 'https://logo.clearbit.com/scalenut.com'),
  ('INK Editor', 'ink-editor', 'AI writing assistant for SEO', 'INK Editor optimizes content for search engines while maintaining quality.', 'https://inkforall.com', cat_writing, 'freemium', 'approved', ARRAY['seo', 'optimization', 'editor'], 'https://logo.clearbit.com/inkforall.com'),
  ('Sudowrite', 'sudowrite', 'AI writing partner for fiction authors', 'Sudowrite helps fiction writers overcome blocks and enhance their stories.', 'https://sudowrite.com', cat_writing, 'paid', 'approved', ARRAY['fiction', 'creative', 'storytelling'], 'https://logo.clearbit.com/sudowrite.com'),
  ('NovelAI', 'novelai', 'AI-powered storytelling and image generation', 'NovelAI assists writers with AI-driven storytelling and character generation.', 'https://novelai.net', cat_writing, 'paid', 'approved', ARRAY['fiction', 'storytelling', 'creative'], 'https://logo.clearbit.com/novelai.net')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- CODING & DEVELOPMENT (20 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('GitHub Copilot', 'github-copilot', 'AI pair programmer that helps you write code faster', 'GitHub Copilot suggests code completions and entire functions as you type, trained on billions of lines of code.', 'https://github.com/features/copilot', cat_coding, 'paid', 'approved', ARRAY['coding', 'autocomplete', 'popular'], 'https://logo.clearbit.com/github.com'),
  ('Cursor', 'cursor', 'AI-first code editor built for pair programming', 'Cursor is a code editor designed around AI, helping you write, edit, and understand code faster.', 'https://cursor.sh', cat_coding, 'freemium', 'approved', ARRAY['coding', 'editor', 'ide'], 'https://logo.clearbit.com/cursor.sh'),
  ('Replit', 'replit', 'AI-powered coding platform in your browser', 'Replit is a collaborative coding platform with AI features for building and deploying apps.', 'https://replit.com', cat_coding, 'freemium', 'approved', ARRAY['coding', 'ide', 'collaboration'], 'https://logo.clearbit.com/replit.com'),
  ('Tabnine', 'tabnine', 'AI code completion for all languages', 'Tabnine provides AI-powered code completions that run locally or in the cloud.', 'https://tabnine.com', cat_coding, 'freemium', 'approved', ARRAY['coding', 'autocomplete', 'privacy'], 'https://logo.clearbit.com/tabnine.com'),
  ('Codeium', 'codeium', 'Free AI code completion and chat', 'Codeium offers free AI-powered code completion and chat for developers.', 'https://codeium.com', cat_coding, 'free', 'approved', ARRAY['coding', 'autocomplete', 'free'], 'https://logo.clearbit.com/codeium.com'),
  ('Amazon CodeWhisperer', 'codewhisperer', 'AI coding companion by AWS', 'CodeWhisperer generates code suggestions and scans for security vulnerabilities.', 'https://aws.amazon.com/codewhisperer', cat_coding, 'freemium', 'approved', ARRAY['aws', 'security', 'coding'], 'https://logo.clearbit.com/aws.amazon.com'),
  ('Sourcegraph Cody', 'sourcegraph-cody', 'AI coding assistant that knows your codebase', 'Cody uses your entire codebase as context for intelligent coding assistance.', 'https://sourcegraph.com/cody', cat_coding, 'freemium', 'approved', ARRAY['codebase', 'context', 'enterprise'], 'https://logo.clearbit.com/sourcegraph.com'),
  ('Codex', 'codex', 'OpenAI''s code generation model', 'Codex translates natural language to code and powers GitHub Copilot.', 'https://openai.com/blog/openai-codex', cat_coding, 'paid', 'approved', ARRAY['api', 'code-generation', 'openai'], 'https://logo.clearbit.com/openai.com'),
  ('Phind', 'phind', 'AI search engine for developers', 'Phind provides AI-powered answers to programming questions with code examples.', 'https://phind.com', cat_coding, 'free', 'approved', ARRAY['search', 'answers', 'free'], 'https://logo.clearbit.com/phind.com'),
  ('AskCodi', 'askcodi', 'AI coding assistant for developers', 'AskCodi helps generate code, documentation, and tests using AI.', 'https://askcodi.com', cat_coding, 'freemium', 'approved', ARRAY['code-generation', 'documentation', 'tests'], 'https://logo.clearbit.com/askcodi.com'),
  ('Blackbox AI', 'blackbox-ai', 'AI code assistant for any language', 'Blackbox AI autocompletes code and answers coding questions across languages.', 'https://blackbox.ai', cat_coding, 'freemium', 'approved', ARRAY['autocomplete', 'multilingual', 'assistant'], 'https://logo.clearbit.com/blackbox.ai'),
  ('Mutable AI', 'mutable-ai', 'AI-accelerated software development', 'Mutable AI transforms codebases and accelerates development with AI.', 'https://mutable.ai', cat_coding, 'freemium', 'approved', ARRAY['refactoring', 'transformation', 'development'], 'https://logo.clearbit.com/mutable.ai'),
  ('Codiga', 'codiga', 'AI code analysis and suggestions', 'Codiga provides real-time code analysis with AI-powered suggestions.', 'https://codiga.io', cat_coding, 'freemium', 'approved', ARRAY['analysis', 'quality', 'suggestions'], 'https://logo.clearbit.com/codiga.io'),
  ('Stenography', 'stenography', 'AI-powered code documentation', 'Stenography automatically documents your codebase using AI.', 'https://stenography.dev', cat_coding, 'freemium', 'approved', ARRAY['documentation', 'automatic', 'comments'], 'https://logo.clearbit.com/stenography.dev'),
  ('Mintlify', 'mintlify', 'AI documentation generator for code', 'Mintlify generates beautiful documentation from your codebase.', 'https://mintlify.com', cat_coding, 'freemium', 'approved', ARRAY['documentation', 'beautiful', 'automatic'], 'https://logo.clearbit.com/mintlify.com'),
  ('Adrenaline', 'adrenaline', 'AI debugger and code explainer', 'Adrenaline helps debug code and explains complex logic using AI.', 'https://useadrenaline.com', cat_coding, 'free', 'approved', ARRAY['debugging', 'explanation', 'learning'], 'https://logo.clearbit.com/useadrenaline.com'),
  ('Codacy', 'codacy', 'AI-powered code quality platform', 'Codacy automatically reviews code quality and identifies issues.', 'https://codacy.com', cat_coding, 'freemium', 'approved', ARRAY['quality', 'review', 'automated'], 'https://logo.clearbit.com/codacy.com'),
  ('Snyk', 'snyk', 'AI-powered security for developers', 'Snyk finds and fixes vulnerabilities in code, dependencies, and containers.', 'https://snyk.io', cat_coding, 'freemium', 'approved', ARRAY['security', 'vulnerabilities', 'scanning'], 'https://logo.clearbit.com/snyk.io'),
  ('DeepCode', 'deepcode', 'AI code review and analysis', 'DeepCode uses AI to find bugs and vulnerabilities in your code.', 'https://snyk.io/product/snyk-code', cat_coding, 'freemium', 'approved', ARRAY['review', 'bugs', 'security'], 'https://logo.clearbit.com/snyk.io'),
  ('Pieces', 'pieces', 'AI-powered developer productivity', 'Pieces saves, enriches, and resurfaces code snippets with AI.', 'https://pieces.app', cat_coding, 'freemium', 'approved', ARRAY['snippets', 'productivity', 'workflow'], 'https://logo.clearbit.com/pieces.app')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- VIDEO & ANIMATION (20 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('Runway', 'runway', 'AI-powered creative tools for video', 'Runway offers AI tools for video editing, generation, and visual effects.', 'https://runway.ml', cat_video, 'freemium', 'approved', ARRAY['video', 'editing', 'vfx'], 'https://logo.clearbit.com/runwayml.com'),
  ('Synthesia', 'synthesia', 'AI video generation with virtual avatars', 'Synthesia creates professional videos with AI avatars from text scripts.', 'https://synthesia.io', cat_video, 'paid', 'approved', ARRAY['video', 'avatars', 'training'], 'https://logo.clearbit.com/synthesia.io'),
  ('HeyGen', 'heygen', 'AI video generator with realistic avatars', 'HeyGen creates spokesperson videos using AI avatars and voice cloning.', 'https://heygen.com', cat_video, 'freemium', 'approved', ARRAY['video', 'avatars', 'marketing'], 'https://logo.clearbit.com/heygen.com'),
  ('Descript', 'descript', 'AI-powered video and podcast editor', 'Descript makes editing video and podcasts as easy as editing a document.', 'https://descript.com', cat_video, 'freemium', 'approved', ARRAY['video', 'podcast', 'editing'], 'https://logo.clearbit.com/descript.com'),
  ('Pika', 'pika', 'AI video generation and editing platform', 'Pika creates and edits videos using AI with text-to-video capabilities.', 'https://pika.art', cat_video, 'freemium', 'approved', ARRAY['video', 'generation', 'creative'], 'https://logo.clearbit.com/pika.art'),
  ('Luma AI', 'luma-ai', '3D capture and AI video generation', 'Luma AI creates 3D scenes from photos and generates AI videos.', 'https://lumalabs.ai', cat_video, 'freemium', 'approved', ARRAY['3d', 'capture', 'video'], 'https://logo.clearbit.com/lumalabs.ai'),
  ('Kapwing', 'kapwing', 'AI video editing in your browser', 'Kapwing offers AI tools for video editing, subtitles, and content creation.', 'https://kapwing.com', cat_video, 'freemium', 'approved', ARRAY['editing', 'browser', 'subtitles'], 'https://logo.clearbit.com/kapwing.com'),
  ('InVideo', 'invideo', 'AI video creation platform', 'InVideo uses AI to help create professional videos from templates.', 'https://invideo.io', cat_video, 'freemium', 'approved', ARRAY['templates', 'creation', 'marketing'], 'https://logo.clearbit.com/invideo.io'),
  ('Pictory', 'pictory', 'AI video creation from text', 'Pictory transforms articles and scripts into engaging videos with AI.', 'https://pictory.ai', cat_video, 'freemium', 'approved', ARRAY['text-to-video', 'articles', 'marketing'], 'https://logo.clearbit.com/pictory.ai'),
  ('Steve AI', 'steve-ai', 'AI-powered animated video creation', 'Steve AI creates animated videos from text using AI characters.', 'https://steve.ai', cat_video, 'freemium', 'approved', ARRAY['animation', 'characters', 'text-to-video'], 'https://logo.clearbit.com/steve.ai'),
  ('Fliki', 'fliki', 'AI video creation with voice synthesis', 'Fliki turns text into videos with AI voices and stock media.', 'https://fliki.ai', cat_video, 'freemium', 'approved', ARRAY['text-to-video', 'voice', 'stock'], 'https://logo.clearbit.com/fliki.ai'),
  ('Colossyan', 'colossyan', 'AI video generator for learning content', 'Colossyan creates training and educational videos with AI presenters.', 'https://colossyan.com', cat_video, 'paid', 'approved', ARRAY['training', 'education', 'presenters'], 'https://logo.clearbit.com/colossyan.com'),
  ('Hour One', 'hour-one', 'AI video generation platform', 'Hour One creates professional videos with AI avatars for business.', 'https://hourone.ai', cat_video, 'paid', 'approved', ARRAY['business', 'avatars', 'professional'], 'https://logo.clearbit.com/hourone.ai'),
  ('D-ID', 'did', 'AI video and avatar creation', 'D-ID creates talking avatar videos from photos using AI.', 'https://d-id.com', cat_video, 'freemium', 'approved', ARRAY['avatars', 'photos', 'talking'], 'https://logo.clearbit.com/d-id.com'),
  ('Elai', 'elai', 'AI video platform for business', 'Elai generates videos with AI presenters from text input.', 'https://elai.io', cat_video, 'freemium', 'approved', ARRAY['business', 'presenters', 'text-to-video'], 'https://logo.clearbit.com/elai.io'),
  ('Opus Clip', 'opus-clip', 'AI video repurposing tool', 'Opus Clip automatically creates short clips from long videos for social media.', 'https://opus.pro', cat_video, 'freemium', 'approved', ARRAY['repurposing', 'shorts', 'social'], 'https://logo.clearbit.com/opus.pro'),
  ('Vidyo AI', 'vidyo-ai', 'AI video repurposing for creators', 'Vidyo AI turns long videos into short clips with AI-powered editing.', 'https://vidyo.ai', cat_video, 'freemium', 'approved', ARRAY['repurposing', 'clips', 'creators'], 'https://logo.clearbit.com/vidyo.ai'),
  ('Topaz Video AI', 'topaz-video', 'AI video upscaling and enhancement', 'Topaz Video AI enhances and upscales video quality using AI.', 'https://topazlabs.com/video-ai', cat_video, 'paid', 'approved', ARRAY['upscaling', 'enhancement', 'quality'], 'https://logo.clearbit.com/topazlabs.com'),
  ('Wonder Dynamics', 'wonder-dynamics', 'AI for VFX and character animation', 'Wonder Dynamics automates VFX and character animation in videos.', 'https://wonderdynamics.com', cat_video, 'paid', 'approved', ARRAY['vfx', 'animation', 'characters'], 'https://logo.clearbit.com/wonderdynamics.com'),
  ('Sora', 'sora', 'OpenAI''s text-to-video AI model', 'Sora generates realistic videos from text descriptions.', 'https://openai.com/sora', cat_video, 'paid', 'approved', ARRAY['text-to-video', 'openai', 'realistic'], 'https://logo.clearbit.com/openai.com')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- AUDIO & MUSIC (20 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('ElevenLabs', 'elevenlabs', 'AI voice generation and cloning', 'ElevenLabs creates realistic AI voices and can clone voices from audio samples.', 'https://elevenlabs.io', cat_audio, 'freemium', 'approved', ARRAY['voice', 'tts', 'cloning', 'popular'], 'https://logo.clearbit.com/elevenlabs.io'),
  ('Suno', 'suno', 'AI music generation from text prompts', 'Suno creates full songs with vocals and instruments from text descriptions.', 'https://suno.ai', cat_audio, 'freemium', 'approved', ARRAY['music', 'generation', 'creative'], 'https://logo.clearbit.com/suno.ai'),
  ('Murf', 'murf', 'AI voice generator for voiceovers', 'Murf creates studio-quality voiceovers using AI voices in multiple languages.', 'https://murf.ai', cat_audio, 'freemium', 'approved', ARRAY['voice', 'voiceover', 'tts'], 'https://logo.clearbit.com/murf.ai'),
  ('AIVA', 'aiva', 'AI music composer for content creators', 'AIVA composes emotional soundtrack music using AI for videos and games.', 'https://aiva.ai', cat_audio, 'freemium', 'approved', ARRAY['music', 'composition', 'soundtrack'], 'https://logo.clearbit.com/aiva.ai'),
  ('Speechify', 'speechify', 'AI text-to-speech reader', 'Speechify converts text to natural-sounding speech for listening to documents and articles.', 'https://speechify.com', cat_audio, 'freemium', 'approved', ARRAY['tts', 'reading', 'accessibility'], 'https://logo.clearbit.com/speechify.com'),
  ('Udio', 'udio', 'AI music creation platform', 'Udio generates high-quality music from text prompts in any genre.', 'https://udio.com', cat_audio, 'freemium', 'approved', ARRAY['music', 'generation', 'genres'], 'https://logo.clearbit.com/udio.com'),
  ('Resemble AI', 'resemble-ai', 'AI voice cloning and generation', 'Resemble AI creates custom AI voices and clones voices for various applications.', 'https://resemble.ai', cat_audio, 'freemium', 'approved', ARRAY['voice', 'cloning', 'custom'], 'https://logo.clearbit.com/resemble.ai'),
  ('Play.ht', 'play-ht', 'AI voice generator and text-to-speech', 'Play.ht offers realistic AI voices for podcasts, videos, and content.', 'https://play.ht', cat_audio, 'freemium', 'approved', ARRAY['tts', 'podcast', 'voices'], 'https://logo.clearbit.com/play.ht'),
  ('Voicemod', 'voicemod', 'Real-time AI voice changer', 'Voicemod transforms your voice in real-time with AI effects and filters.', 'https://voicemod.net', cat_audio, 'freemium', 'approved', ARRAY['voice-changer', 'real-time', 'effects'], 'https://logo.clearbit.com/voicemod.net'),
  ('Lovo', 'lovo', 'AI voiceover and text-to-speech platform', 'Lovo creates professional voiceovers with AI in 100+ languages.', 'https://lovo.ai', cat_audio, 'freemium', 'approved', ARRAY['voiceover', 'multilingual', 'professional'], 'https://logo.clearbit.com/lovo.ai'),
  ('Soundraw', 'soundraw', 'AI music generation for creators', 'Soundraw generates royalty-free music customized to your needs.', 'https://soundraw.io', cat_audio, 'freemium', 'approved', ARRAY['music', 'royalty-free', 'customization'], 'https://logo.clearbit.com/soundraw.io'),
  ('Boomy', 'boomy', 'AI music creation for everyone', 'Boomy lets anyone create and release original songs with AI.', 'https://boomy.com', cat_audio, 'freemium', 'approved', ARRAY['music', 'creation', 'release'], 'https://logo.clearbit.com/boomy.com'),
  ('Amper Music', 'amper-music', 'AI music composition platform', 'Amper creates custom music tracks using AI for videos and content.', 'https://shutterstock.com/discover/ampermusic', cat_audio, 'paid', 'approved', ARRAY['music', 'composition', 'custom'], 'https://logo.clearbit.com/shutterstock.com'),
  ('Beatoven', 'beatoven', 'AI music for video content', 'Beatoven creates mood-based music for videos using AI.', 'https://beatoven.ai', cat_audio, 'freemium', 'approved', ARRAY['music', 'video', 'mood'], 'https://logo.clearbit.com/beatoven.ai'),
  ('WellSaid Labs', 'wellsaid-labs', 'Enterprise AI voice studio', 'WellSaid Labs creates enterprise-grade AI voices for professional content.', 'https://wellsaidlabs.com', cat_audio, 'enterprise', 'approved', ARRAY['enterprise', 'voice', 'professional'], 'https://logo.clearbit.com/wellsaidlabs.com'),
  ('Descript Overdub', 'descript-overdub', 'AI voice cloning for editing', 'Overdub creates a clone of your voice for seamless audio editing.', 'https://descript.com/overdub', cat_audio, 'paid', 'approved', ARRAY['cloning', 'editing', 'overdub'], 'https://logo.clearbit.com/descript.com'),
  ('Podcastle', 'podcastle', 'AI podcast creation platform', 'Podcastle offers AI tools for podcast recording, editing, and enhancement.', 'https://podcastle.ai', cat_audio, 'freemium', 'approved', ARRAY['podcast', 'editing', 'enhancement'], 'https://logo.clearbit.com/podcastle.ai'),
  ('Adobe Podcast', 'adobe-podcast', 'AI audio enhancement by Adobe', 'Adobe Podcast uses AI to enhance audio quality and remove noise.', 'https://podcast.adobe.com', cat_audio, 'free', 'approved', ARRAY['enhancement', 'noise-removal', 'adobe'], 'https://logo.clearbit.com/adobe.com'),
  ('Cleanvoice', 'cleanvoice', 'AI audio cleaning for podcasts', 'Cleanvoice removes filler words, silence, and noise from recordings.', 'https://cleanvoice.ai', cat_audio, 'freemium', 'approved', ARRAY['cleaning', 'podcast', 'filler-removal'], 'https://logo.clearbit.com/cleanvoice.ai'),
  ('Krisp', 'krisp', 'AI noise cancellation for calls', 'Krisp removes background noise from calls in real-time using AI.', 'https://krisp.ai', cat_audio, 'freemium', 'approved', ARRAY['noise-cancellation', 'calls', 'real-time'], 'https://logo.clearbit.com/krisp.ai')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- PRODUCTIVITY (20 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('Notion AI', 'notion-ai', 'AI writing assistant built into Notion', 'Notion AI helps you write, brainstorm, and organize within your Notion workspace.', 'https://notion.so/product/ai', cat_productivity, 'paid', 'approved', ARRAY['writing', 'notes', 'organization'], 'https://logo.clearbit.com/notion.so'),
  ('Otter.ai', 'otter-ai', 'AI meeting transcription and notes', 'Otter.ai automatically transcribes meetings and generates summaries and action items.', 'https://otter.ai', cat_productivity, 'freemium', 'approved', ARRAY['transcription', 'meetings', 'notes'], 'https://logo.clearbit.com/otter.ai'),
  ('Mem', 'mem', 'AI-powered personal knowledge base', 'Mem organizes your notes and surfaces relevant information using AI.', 'https://mem.ai', cat_productivity, 'freemium', 'approved', ARRAY['notes', 'knowledge', 'organization'], 'https://logo.clearbit.com/mem.ai'),
  ('Reclaim', 'reclaim', 'AI calendar scheduling assistant', 'Reclaim automatically schedules tasks, habits, and meetings on your calendar.', 'https://reclaim.ai', cat_productivity, 'freemium', 'approved', ARRAY['calendar', 'scheduling', 'time'], 'https://logo.clearbit.com/reclaim.ai'),
  ('Taskade', 'taskade', 'AI-powered productivity workspace', 'Taskade combines task management, notes, and AI assistance in one platform.', 'https://taskade.com', cat_productivity, 'freemium', 'approved', ARRAY['tasks', 'collaboration', 'notes'], 'https://logo.clearbit.com/taskade.com'),
  ('Fireflies', 'fireflies', 'AI meeting assistant and note-taker', 'Fireflies records, transcribes, and summarizes meetings automatically.', 'https://fireflies.ai', cat_productivity, 'freemium', 'approved', ARRAY['meetings', 'transcription', 'summary'], 'https://logo.clearbit.com/fireflies.ai'),
  ('Grain', 'grain', 'AI video highlights from meetings', 'Grain captures and shares highlights from video meetings using AI.', 'https://grain.com', cat_productivity, 'freemium', 'approved', ARRAY['meetings', 'highlights', 'video'], 'https://logo.clearbit.com/grain.com'),
  ('Clockwise', 'clockwise', 'AI calendar optimization', 'Clockwise uses AI to protect focus time and optimize meeting schedules.', 'https://clockwise.com', cat_productivity, 'freemium', 'approved', ARRAY['calendar', 'focus', 'optimization'], 'https://logo.clearbit.com/clockwise.com'),
  ('Motion', 'motion', 'AI project and task management', 'Motion uses AI to automatically plan your day and prioritize tasks.', 'https://usemotion.com', cat_productivity, 'paid', 'approved', ARRAY['planning', 'tasks', 'automation'], 'https://logo.clearbit.com/usemotion.com'),
  ('Reflect', 'reflect', 'AI-powered note-taking app', 'Reflect uses AI to help you think and connect ideas in your notes.', 'https://reflect.app', cat_productivity, 'paid', 'approved', ARRAY['notes', 'thinking', 'connections'], 'https://logo.clearbit.com/reflect.app'),
  ('Tldv', 'tldv', 'AI meeting recorder for Google Meet and Zoom', 'tldv records, transcribes, and summarizes video meetings with AI.', 'https://tldv.io', cat_productivity, 'freemium', 'approved', ARRAY['meetings', 'recording', 'transcription'], 'https://logo.clearbit.com/tldv.io'),
  ('Cogram', 'cogram', 'AI note-taker for virtual meetings', 'Cogram takes notes and identifies action items in meetings automatically.', 'https://cogram.com', cat_productivity, 'paid', 'approved', ARRAY['meetings', 'notes', 'actions'], 'https://logo.clearbit.com/cogram.com'),
  ('Magical', 'magical', 'AI productivity for repetitive tasks', 'Magical automates repetitive tasks and messaging with AI.', 'https://getmagical.com', cat_productivity, 'freemium', 'approved', ARRAY['automation', 'messaging', 'repetitive'], 'https://logo.clearbit.com/getmagical.com'),
  ('Tana', 'tana', 'AI-powered knowledge management', 'Tana is an all-in-one workspace for notes, tasks, and knowledge.', 'https://tana.inc', cat_productivity, 'freemium', 'approved', ARRAY['knowledge', 'notes', 'workspace'], 'https://logo.clearbit.com/tana.inc'),
  ('Personal AI', 'personal-ai', 'AI that learns from your data', 'Personal AI creates a personal AI model trained on your messages and documents.', 'https://personal.ai', cat_productivity, 'freemium', 'approved', ARRAY['personal', 'learning', 'memory'], 'https://logo.clearbit.com/personal.ai'),
  ('SaneBox', 'sanebox', 'AI email management', 'SaneBox uses AI to sort email and surface what matters most.', 'https://sanebox.com', cat_productivity, 'paid', 'approved', ARRAY['email', 'sorting', 'priority'], 'https://logo.clearbit.com/sanebox.com'),
  ('Superhuman', 'superhuman', 'AI-powered email experience', 'Superhuman is the fastest email app with AI-powered features.', 'https://superhuman.com', cat_productivity, 'paid', 'approved', ARRAY['email', 'speed', 'productivity'], 'https://logo.clearbit.com/superhuman.com'),
  ('Zapier AI', 'zapier-ai', 'AI automation for workflows', 'Zapier uses AI to help build and optimize automation workflows.', 'https://zapier.com/ai', cat_productivity, 'freemium', 'approved', ARRAY['automation', 'workflows', 'integration'], 'https://logo.clearbit.com/zapier.com'),
  ('Make AI', 'make-ai', 'AI-powered workflow automation', 'Make uses AI to help design and optimize complex automations.', 'https://make.com', cat_productivity, 'freemium', 'approved', ARRAY['automation', 'workflows', 'visual'], 'https://logo.clearbit.com/make.com'),
  ('Bardeen', 'bardeen', 'AI workflow automation browser extension', 'Bardeen automates repetitive tasks with AI-powered browser workflows.', 'https://bardeen.ai', cat_productivity, 'freemium', 'approved', ARRAY['automation', 'browser', 'workflows'], 'https://logo.clearbit.com/bardeen.ai')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- DESIGN & CREATIVE (17 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('Canva', 'canva', 'Design platform with AI-powered features', 'Canva makes design easy with templates and AI tools for image generation and editing.', 'https://canva.com', cat_design, 'freemium', 'approved', ARRAY['design', 'graphics', 'templates', 'popular'], 'https://logo.clearbit.com/canva.com'),
  ('Figma AI', 'figma-ai', 'AI features for UI/UX design in Figma', 'Figma AI adds intelligent features to the popular design tool for faster workflows.', 'https://figma.com', cat_design, 'freemium', 'approved', ARRAY['design', 'ui', 'ux'], 'https://logo.clearbit.com/figma.com'),
  ('Khroma', 'khroma', 'AI color palette generator', 'Khroma learns your color preferences and generates unlimited palettes you''ll love.', 'https://khroma.co', cat_design, 'free', 'approved', ARRAY['design', 'colors', 'palette'], 'https://logo.clearbit.com/khroma.co'),
  ('Looka', 'looka', 'AI-powered logo maker', 'Looka creates professional logos and brand identity using AI.', 'https://looka.com', cat_design, 'freemium', 'approved', ARRAY['logo', 'branding', 'design'], 'https://logo.clearbit.com/looka.com'),
  ('Uizard', 'uizard', 'AI-powered UI design tool', 'Uizard transforms sketches and screenshots into editable UI designs using AI.', 'https://uizard.io', cat_design, 'freemium', 'approved', ARRAY['ui', 'prototyping', 'design'], 'https://logo.clearbit.com/uizard.io'),
  ('Galileo AI', 'galileo-ai', 'AI-generated UI designs from text', 'Galileo AI creates editable UI designs from natural language descriptions.', 'https://usegalileo.ai', cat_design, 'paid', 'approved', ARRAY['ui', 'generation', 'text-to-design'], 'https://logo.clearbit.com/usegalileo.ai'),
  ('Framer AI', 'framer-ai', 'AI website builder', 'Framer uses AI to generate website designs and copy from descriptions.', 'https://framer.com/ai', cat_design, 'freemium', 'approved', ARRAY['website', 'generation', 'no-code'], 'https://logo.clearbit.com/framer.com'),
  ('Designs.ai', 'designs-ai', 'AI design suite for creatives', 'Designs.ai offers AI tools for logos, videos, mockups, and more.', 'https://designs.ai', cat_design, 'freemium', 'approved', ARRAY['suite', 'logos', 'videos'], 'https://logo.clearbit.com/designs.ai'),
  ('Brandmark', 'brandmark', 'AI logo design and branding', 'Brandmark uses AI to create unique logos and brand identities.', 'https://brandmark.io', cat_design, 'paid', 'approved', ARRAY['logo', 'branding', 'identity'], 'https://logo.clearbit.com/brandmark.io'),
  ('Hatchful', 'hatchful', 'Free AI logo maker by Shopify', 'Hatchful creates professional logos for free using AI.', 'https://hatchful.shopify.com', cat_design, 'free', 'approved', ARRAY['logo', 'free', 'shopify'], 'https://logo.clearbit.com/shopify.com'),
  ('Piktochart', 'piktochart', 'AI infographic and presentation maker', 'Piktochart uses AI to help create infographics and presentations.', 'https://piktochart.com', cat_design, 'freemium', 'approved', ARRAY['infographics', 'presentations', 'visual'], 'https://logo.clearbit.com/piktochart.com'),
  ('Visme', 'visme', 'AI visual content creation', 'Visme offers AI tools for presentations, infographics, and documents.', 'https://visme.co', cat_design, 'freemium', 'approved', ARRAY['presentations', 'infographics', 'documents'], 'https://logo.clearbit.com/visme.co'),
  ('Recraft', 'recraft', 'AI design tool for graphics', 'Recraft generates vector art, icons, and illustrations using AI.', 'https://recraft.ai', cat_design, 'freemium', 'approved', ARRAY['vector', 'icons', 'illustrations'], 'https://logo.clearbit.com/recraft.ai'),
  ('Autodraw', 'autodraw', 'AI drawing assistant by Google', 'Autodraw turns your rough sketches into polished drawings using AI.', 'https://autodraw.com', cat_design, 'free', 'approved', ARRAY['drawing', 'google', 'free'], 'https://logo.clearbit.com/google.com'),
  ('Magician', 'magician', 'AI design assistant for Figma', 'Magician adds AI superpowers to Figma for icons, copy, and images.', 'https://magician.design', cat_design, 'paid', 'approved', ARRAY['figma', 'plugin', 'assistant'], 'https://logo.clearbit.com/magician.design'),
  ('Let''s Enhance', 'lets-enhance', 'AI image upscaling and enhancement', 'Let''s Enhance upscales and improves image quality using AI.', 'https://letsenhance.io', cat_design, 'freemium', 'approved', ARRAY['upscaling', 'enhancement', 'quality'], 'https://logo.clearbit.com/letsenhance.io'),
  ('Remove.bg', 'remove-bg', 'AI background removal', 'Remove.bg automatically removes backgrounds from images using AI.', 'https://remove.bg', cat_design, 'freemium', 'approved', ARRAY['background', 'removal', 'automatic'], 'https://logo.clearbit.com/remove.bg')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

  -- =============================================
  -- MARKETING & SEO (15 tools)
  -- =============================================
  INSERT INTO tools (name, slug, tagline, description, website_url, category_id, pricing_type, status, tags, logo_url) VALUES
  ('Surfer SEO', 'surfer-seo', 'AI-powered SEO content optimization', 'Surfer SEO analyzes top-ranking pages and helps you optimize content for search engines.', 'https://surferseo.com', cat_marketing, 'paid', 'approved', ARRAY['seo', 'content', 'optimization'], 'https://logo.clearbit.com/surferseo.com'),
  ('Clearscope', 'clearscope', 'AI content optimization for SEO', 'Clearscope helps you create content that ranks by analyzing top-performing pages.', 'https://clearscope.io', cat_marketing, 'paid', 'approved', ARRAY['seo', 'content', 'writing'], 'https://logo.clearbit.com/clearscope.io'),
  ('Frase', 'frase', 'AI content research and writing tool', 'Frase helps you research, write, and optimize content for search engines.', 'https://frase.io', cat_marketing, 'freemium', 'approved', ARRAY['seo', 'research', 'writing'], 'https://logo.clearbit.com/frase.io'),
  ('MarketMuse', 'marketmuse', 'AI content strategy platform', 'MarketMuse uses AI to plan content strategy and identify gaps in your coverage.', 'https://marketmuse.com', cat_marketing, 'paid', 'approved', ARRAY['content', 'strategy', 'seo'], 'https://logo.clearbit.com/marketmuse.com'),
  ('Phrasee', 'phrasee', 'AI copywriting for email marketing', 'Phrasee generates and optimizes email subject lines and copy using AI.', 'https://phrasee.co', cat_marketing, 'enterprise', 'approved', ARRAY['email', 'copywriting', 'marketing'], 'https://logo.clearbit.com/phrasee.co'),
  ('Persado', 'persado', 'AI language generation for marketing', 'Persado generates marketing language that resonates with target audiences.', 'https://persado.com', cat_marketing, 'enterprise', 'approved', ARRAY['language', 'personalization', 'enterprise'], 'https://logo.clearbit.com/persado.com'),
  ('Seventh Sense', 'seventh-sense', 'AI email send time optimization', 'Seventh Sense optimizes email delivery times using AI for better engagement.', 'https://theseventhsense.com', cat_marketing, 'paid', 'approved', ARRAY['email', 'timing', 'optimization'], 'https://logo.clearbit.com/theseventhsense.com'),
  ('Albert AI', 'albert-ai', 'AI digital marketing optimization', 'Albert AI autonomously optimizes digital marketing campaigns across channels.', 'https://albert.ai', cat_marketing, 'enterprise', 'approved', ARRAY['campaigns', 'optimization', 'autonomous'], 'https://logo.clearbit.com/albert.ai'),
  ('Pathmatics', 'pathmatics', 'AI digital advertising intelligence', 'Pathmatics provides AI-powered insights into competitor advertising strategies.', 'https://pathmatics.com', cat_marketing, 'enterprise', 'approved', ARRAY['advertising', 'intelligence', 'competitors'], 'https://logo.clearbit.com/pathmatics.com'),
  ('Smartly.io', 'smartly-io', 'AI-powered social advertising', 'Smartly.io automates and optimizes social media advertising with AI.', 'https://smartly.io', cat_marketing, 'enterprise', 'approved', ARRAY['social', 'advertising', 'automation'], 'https://logo.clearbit.com/smartly.io'),
  ('Adzooma', 'adzooma', 'AI PPC management platform', 'Adzooma uses AI to optimize Google, Facebook, and Microsoft Ads campaigns.', 'https://adzooma.com', cat_marketing, 'freemium', 'approved', ARRAY['ppc', 'optimization', 'ads'], 'https://logo.clearbit.com/adzooma.com'),
  ('Lately', 'lately', 'AI social media content generator', 'Lately uses AI to repurpose long-form content into social media posts.', 'https://lately.ai', cat_marketing, 'paid', 'approved', ARRAY['social', 'content', 'repurposing'], 'https://logo.clearbit.com/lately.ai'),
  ('Optimove', 'optimove', 'AI customer marketing platform', 'Optimove uses AI to orchestrate personalized customer marketing campaigns.', 'https://optimove.com', cat_marketing, 'enterprise', 'approved', ARRAY['customer', 'personalization', 'campaigns'], 'https://logo.clearbit.com/optimove.com'),
  ('Drift', 'drift', 'AI conversational marketing platform', 'Drift uses AI chatbots and assistants for conversational marketing and sales.', 'https://drift.com', cat_marketing, 'paid', 'approved', ARRAY['chatbot', 'conversational', 'sales'], 'https://logo.clearbit.com/drift.com'),
  ('Jasper for Marketing', 'jasper-marketing', 'AI marketing content platform', 'Jasper helps marketing teams create campaigns, copy, and content at scale.', 'https://jasper.ai/marketing', cat_marketing, 'paid', 'approved', ARRAY['content', 'marketing', 'teams'], 'https://logo.clearbit.com/jasper.ai')
  ON CONFLICT (slug) DO UPDATE SET logo_url = EXCLUDED.logo_url, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

END $$;

-- Update click counts for popular tools (makes homepage look active)
UPDATE tools SET click_count = floor(random() * 500 + 100)::int WHERE status = 'approved';
UPDATE tools SET upvotes = floor(random() * 100 + 10)::int WHERE status = 'approved';

-- Mark some tools as featured for initial display
UPDATE tools SET is_featured = true, is_verified = true
WHERE slug IN ('chatgpt', 'claude', 'midjourney', 'github-copilot', 'elevenlabs', 'notion-ai', 'canva', 'runway', 'grammarly', 'dall-e-3');
